using SFML.Graphics;

namespace nk.Res {
	public static class Img {
		public static class Icon {
			public static class ItemUse {
				private static NamedTexture refill; public static NamedTexture Refill { get { return refill; } }
				private static NamedTexture consum; public static NamedTexture Consum { get { return consum; } }

				static ItemUse() {
					Texture refillTexture = 
				}
			}
		}
	}
}
