namespace nk.Client {
	public class NeekoGG : WindowBase {
		public const uint DEFAULT_WINDOW_WIDTH  = 1600;
		public const uint DEFAULT_WINDOW_HEIGHT = 900;

		public const string WINDOW_TITLE = "Neeko.GG";

		public NeekoGG() : base (DEFAULT_WINDOW_WIDTH, DEFAULT_WINDOW_HEIGHT, WINDOW_TITLE) {}

		public override void LoadContent() {
		}

		public override void Initialize() {
		}

		public override void Update(GameTime _gameTime) {
		}

		public override void Draw(GameTime gameTime) {
		}
	}
}
